export const books = [
  {
    id: 1,
    name: "এক ডজন মননশীল শ্রুতিনাটক ও একাঙ্ক নাটক",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "159",
    pdfLocation: "/pdf/একডজন_মাননশীল_শ্রুতি_ও_একাঙ্কনাটক.pdf",
    bookType: "নাটক",
    price: "একশত কুড়ি ",
    imageLocation: "/image/books/akdojonnatak.jpg",
  },
  {
    id: 2,
    name: "খেয়াল-খুশি",
    publiser: "প্রভা প্রকাশনী",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "/pdf/খেয়াল_খুশি.pdf",
    bookType: "poem",
    price: "50",
    imageLocation: "/image/books/khealkhusi.jpg",
  },
  {
    id: 3,
    name: "না মেয়েমানুষের কাহিনি",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "208",
    pdfLocation: "/pdf/.pdf",
    bookType: "uponash",
    price: "200",
    imageLocation: "/image/books/mayemanush.jpg",
  },
  {
    id: 4,
    name: "টাড় বনের উপকথা (আবৃত্তিযোগ্য আঞ্চলিক কবিতাগুচ্ছ)",
    publiser: "পত্রলেখা",
    pubiserAddress: "১০বি কলেজ রো কলকাতা ৭০০ ০০৯",
    pageNumber: "87",
    pdfLocation: "/pdf/টাড়_বোনের_উপকথা.pdf",
    bookType: "কবিতা",
    price: "চল্লিশ",
    imageLocation: "/image/books/upakatha.jpg",
  },
  {
    id: 5,
    name: "ম্যানগ্রোভ",
    publiser: "অর্পিতা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "176",
    pdfLocation: "/pdf/ম্যানগ্রোভ.pdf",
    bookType: "উপন্যাস",
    price: "একশত পঞ্চাশ",
    imageLocation: "/image/books/mangrove.jpg",
  },
  {
    id: 6,
    name: "মায়াবী রোদ্দুর",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "72",
    pdfLocation: "/pdf/মায়াবী_রোদ্দুর.pdf",
    bookType: "কবিতা",
    price: "পঞ্চাশ",
    imageLocation: "/image/books/mayabiraddur.jpg",
  },
  {
    id: 7,
    name: "নব আলোকে নিবেদিতা",
    publiser: "গীতাঞ্জলি",
    pubiserAddress: "ভবানী দত্ত লেন, স্টল নং-২৬, কলকাতা-৭০০০৭৩",
    pageNumber: "138",
    pdfLocation: "/pdf/নবআলোকে_নিবেদিতা.pdf",
    bookType: "প্রবন্ধ",
    price: "একশত কুড়ি",
    imageLocation: "/image/books/nibedita.jpg",
  },
  {
    id: 8,
    name: "মৃত্যুলোক মৃত্যুশোক 3 মৃত্যুঞ্জয় রবীন্দ্রনাথ",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "431",
    pdfLocation: "/pdf/রবীন্দ্রনাথ.pdf",
    bookType: "probondho",
    price: "400",
    imageLocation: "/image/books/rabindranath.jpg",
  },

  {
    id: 10,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/adimghran.jpg",
  },
  {
    id: 11,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/panchitinatak.jpg",
  },
  {
    id: 12,
    name: "যুগনায়ক বিবেকানন্দ",
    publiser: "চিকিতুষি প্রকাশনী ",
    pubiserAddress: "পূর্ববৈদ্যপাড়া, সোনারপুর, কলকাতা-১৫০",
    pageNumber: "96",
    pdfLocation: "#",
    bookType: "নাটক",
    price: "একশত কুড়ি ",
    imageLocation: "/image/books/vibekananda.jpg",
  },
  {
    id: 13,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/hridoykhuri.jpg",
  },
  {
    id: 14,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/rupantarkami.jpg",
  },
  {
    id: 15,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/kabita150.jpg",
  },
  {
    id: 16,
    name: "",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "",
    pdfLocation: "#",
    bookType: "",
    price: "",
    imageLocation: "/image/books/jajabar.jpg",
  },
  {
    id: 17,
    name: "শ্রীমদভগবদগীতা ও মার্ক্সবাদ",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "66",
    pdfLocation: "/pdf/শ্রীমদভগবদগীতা_ও_মার্ক্সবাদ.pdf",
    bookType: "probondho",
    price: "100",
    imageLocation: "/image/books/",
  },
  {
    id: 18,
    name: "শ্রীমদভগবাদগীতা ও দিব্যজীবন",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "191",
    pdfLocation: "/pdf/শ্রীমদভগবাদগীতা_ও_দিব্যজীবন.pdf",
    bookType: "probondho",
    price: "250",
    imageLocation: "/image/books/",
  },
  {
    id: 19,
    name: "সংশয়বাদীর শত প্রশ্ন ও গীতাধ্যানীর সদুত্তর",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "146",
    pdfLocation: "/pdf/সংশয়বাদীর_শত_প্রশ্ন_ও_গীতাধ্যানীর_সদুত্তর.pdf",
    bookType: "probondho",
    price: "150",
    imageLocation: "/image/books/",
  },
  {
    id: 20,
    name: "সীমদভগবদগীতা ও দেহতত্ত্ববাদ",
    publiser: "প্রভা প্রকাশনী ",
    pubiserAddress: "১কে, রাধানাথ মল্লিক লেন, কলকাতা-১২",
    pageNumber: "88",
    pdfLocation: "/pdf/সীমদভগবদগীতা_ও_দেহতত্ত্ববাদ.pdf",
    bookType: "probondho",
    price: "100",
    imageLocation: "/image/books/",
  },
];
